version: '3.3'
services:
  website:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website-web
    image: website-web
    ports:
      - 8000:80
    volumes:
      - web:/var/www/html/website
    links:
      - website-db
      - website-redis
    env_file:
      - .env.web
  website-db:
    restart: always
    image: mysql:5.7
    secrets:
      - root_passwd
      - db_passwd
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    container_name: website-db
    #ports:
    #  - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/root_passwd
      MYSQL_PASSWORD_FILE: /run/secrets/db_passwd
    volumes:
      - db:/var/lib/mysql
  website-redis:
    restart: always
    image: redis:5-alpine
    container_name: website-redis
    #ports:
    #  - 6379:6379
    volumes:
      - redis:/data
volumes:
    web:
    db:
    redis:

secrets:
  root_passwd:
    external: true
  db_passwd:
    external: true
