version: '3'
services:
  website:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website-web
    image: website-web
    ports:
      - 8000:80
    links:
      - website-db
    env_file:
      - .env.db
  website-db:
    restart: always
    image: mysql:5.7
    container_name: website-db
    #ports:
    #  - 3306:3306
    env_file:
      - .env.db
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - website-db
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=website-db
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: website-phpmyadmin
volumes:
    web:
    db:
